/* ===== DLH NEXUS - Tools & Device Control ===== */

const NexusTools = {
    connectors: [
        { id: 'weather', name: 'Weather', icon: '🌤️', desc: 'Get weather for any location', available: true,
            action: async (q) => { const r = await fetch(`https://wttr.in/${encodeURIComponent(q)}?format=3`); return await r.text(); } },
        { id: 'calculator', name: 'Calculator', icon: '🧮', desc: 'Mathematical calculations', available: true,
            action: async (q) => { const s = q.replace(/[^0-9+\-*/.()^% ]/g,''); return String(Function('"use strict";return ('+s+')')()); } },
        { id: 'translator', name: 'Translator', icon: '🌐', desc: 'Translate between languages', available: true,
            action: async (q) => { const r = await fetch(`https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q=${encodeURIComponent(q)}`); const d = await r.json(); return d[0].map(t=>t[0]).join(''); } },
        { id: 'ip-info', name: 'IP Info', icon: '📡', desc: 'Get IP address info', available: true,
            action: async () => { const r = await fetch('https://api.ipify.org?format=json'); const d = await r.json(); return 'IP: ' + d.ip; } },
        { id: 'timestamp', name: 'Timestamp', icon: '⏰', desc: 'Current time and date', available: true,
            action: async () => { const n = new Date(); return `Time: ${n.toLocaleString()}\nUnix: ${Math.floor(n.getTime()/1000)}`; } },
        { id: 'uuid', name: 'UUID Generator', icon: '🎲', desc: 'Generate random UUIDs', available: true,
            action: async () => crypto.randomUUID() },
        { id: 'qr', name: 'QR Generator', icon: '📱', desc: 'Generate QR codes', available: true,
            action: async (q) => `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(q)}` },
        { id: 'password', name: 'Password Gen', icon: '🔑', desc: 'Generate secure passwords', available: true,
            action: async () => { const c='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*'; let p=''; for(let i=0;i<16;i++) p+=c[Math.floor(Math.random()*c.length)]; return p; } },
        { id: 'color', name: 'Color Tool', icon: '🎨', desc: 'Color conversion and info', available: true,
            action: async (q) => { const c = q.match(/#?[0-9a-fA-F]{6}/); if(!c) return 'Enter a hex color like #FF0000'; const h=c[0].replace('#',''); const r=parseInt(h.substr(0,2),16),g=parseInt(h.substr(2,2),16),b=parseInt(h.substr(4,2),16); return `RGB: ${r}, ${g}, ${b}`; } },
        { id: 'base64', name: 'Base64', icon: '📝', desc: 'Encode/decode Base64', available: true,
            action: async (q) => { if(q.startsWith('decode:')) return atob(q.slice(7)); return btoa(q); } },
    ],

    devices: [
        { id: 'camera', name: 'Camera', icon: '📷', desc: 'Access device camera',
            check: () => !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia),
            activate: async () => { const s = await navigator.mediaDevices.getUserMedia({video:true}); return {success:true, data:'Camera stream active'}; } },
        { id: 'mic', name: 'Microphone', icon: '🎤', desc: 'Access device microphone',
            check: () => !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia),
            activate: async () => { const s = await navigator.mediaDevices.getUserMedia({audio:true}); return {success:true, data:'Microphone active'}; } },
        { id: 'geo', name: 'Geolocation', icon: '📍', desc: 'Get device location',
            check: () => !!navigator.geolocation,
            activate: () => new Promise((res) => { navigator.geolocation.getCurrentPosition(p => res({success:true, data:`Lat: ${p.coords.latitude}, Lon: ${p.coords.longitude}`}), e => res({success:false, error:e.message}), {timeout:10000}); }) },
        { id: 'battery', name: 'Battery', icon: '🔋', desc: 'Check battery status',
            check: () => !!navigator.getBattery,
            activate: async () => { const b = await navigator.getBattery(); return {success:true, data:`Level: ${Math.round(b.level*100)}%, Charging: ${b.charging}`}; } },
        { id: 'vibrate', name: 'Vibration', icon: '📳', desc: 'Trigger device vibration',
            check: () => !!navigator.vibrate,
            activate: async () => { navigator.vibrate([100,50,100,50,200]); return {success:true, data:'Vibration triggered'}; } },
        { id: 'fullscreen', name: 'Fullscreen', icon: '🖥️', desc: 'Toggle fullscreen mode',
            check: () => !!document.documentElement.requestFullscreen,
            activate: async () => { if(!document.fullscreenElement){ await document.documentElement.requestFullscreen(); return {success:true, data:'Fullscreen enabled'}; } else { await document.exitFullscreen(); return {success:true, data:'Fullscreen disabled'}; } } },
        { id: 'screen', name: 'Screen Capture', icon: '📸', desc: 'Capture screen content',
            check: () => !!(navigator.mediaDevices && navigator.mediaDevices.getDisplayMedia),
            activate: async () => { const s = await navigator.mediaDevices.getDisplayMedia({video:true}); return {success:true, data:'Screen capture active'}; } },
        { id: 'clipboard', name: 'Clipboard', icon: '📋', desc: 'Read clipboard content',
            check: () => !!navigator.clipboard,
            activate: async () => { const t = await navigator.clipboard.readText(); return {success:true, data:t||'Clipboard empty'}; } },
        { id: 'network', name: 'Network Info', icon: '📶', desc: 'Check network status',
            check: () => !!navigator.connection,
            activate: async () => { const c = navigator.connection; return {success:true, data:`Type: ${c.effectiveType}, Downlink: ${c.downlink}Mbps, RTT: ${c.rtt}ms`}; } },
        { id: 'speech', name: 'Speech Output', icon: '🔊', desc: 'Text-to-speech via browser',
            check: () => !!('speechSynthesis' in window),
            activate: async () => { const u = new SpeechSynthesisUtterance('DLH NEXUS is online'); speechSynthesis.speak(u); return {success:true, data:'Speaking'}; } },
        { id: 'notify', name: 'Notifications', icon: '🔔', desc: 'Send browser notifications',
            check: () => !!('Notification' in window),
            activate: async () => { if(Notification.permission==='granted'){ new Notification('DLH NEXUS',{body:'Notifications active'}); return {success:true,data:'Sent'}; } const p=await Notification.requestPermission(); if(p==='granted'){ new Notification('DLH NEXUS',{body:'Notifications active'}); return {success:true,data:'Sent'}; } return {success:false,error:'Permission denied'}; } },
        { id: 'info', name: 'Device Info', icon: 'ℹ️', desc: 'Device and browser information',
            check: () => true,
            activate: async () => { return {success:true, data:`Platform: ${navigator.platform}\nLanguage: ${navigator.language}\nScreen: ${screen.width}×${screen.height}\nViewport: ${window.innerWidth}×${window.innerHeight}\nCores: ${navigator.hardwareConcurrency||'N/A'}\nOnline: ${navigator.onLine}`}; } },
    ],

    initDevices() {
        this.devices.forEach(d => { d.available = d.check(); });
    }
};

window.NexusTools = NexusTools;
